export const initialOpts = {
    title: '',
    msg: '',
    type: 'info',
    closeButton: true,
    debug: false,
    positionClass: 'toast-top-right',
    showDuration: 600,
    hideDuration: 400,
    timeOut: 6000,
    extendedTimeOut: 1000,
    showEasing: 'swing',
    hideEasing: 'linear',
    showMethod: 'fadeIn',
    hideMethod: 'fadeOut',
    onclick: null,
    className: '',
    closeDuration: 200,
    onlyOne: false,
    clear: false,
};
